### PR TITLE
add kerberos authentication

### PR DESCRIPTION
**Pull request by nicph**
This enable kerberos authentication if the urllib2_kerberos module is installed. Please review.

### CODE REVIEW

**Comment by nsmgr8** [comment]
This is a great contribution. Thank you very much.

There are two main issues here. 
1. It will break Basic HTTP Authentication.
2. Documentation is missing.

I think we need to generalise the server type selection. We may add server type to the server config dictionary, instead of guessing from the auth value.

**Comment by nicph** [comment]
I don't believe that basic authentication will be broken, since this is only an additional authentication handler. I have no trac server with basic authentication available for tests, but it should work as usual. I made it so to keep compatibility with current configuration style.

About documentation, it has been planned on my todo list and will pop it as soon as possible. I will maybe wait for any evolution on the server config dictionary ?

**Comment by nsmgr8** [comment]
I do not know much about kerberos. Does kerberos auth handle basic auth also? Because here if we have urllib2_kerberos installed, the basic auth ServerProxy always gets the kerberos transport. That is why I doubted. I will try to test it later when I have windows somewhere. If kerberos can handle basic auth by default then this is good code.

About documentation I meant to add some text in doc/vitra.txt file to let user know it supports kerberos auth.

However, I think we do need to change server config dictionary for more server type in future.

**Comment by nsmgr8** [comment]
If it works with Basic Auth, adding server type into config dict is a seperate issue.

**Comment by nsmgr8** [comment]
Error for basic auth

Yes, it breaks basic auth. See the screenshot. It doesn't even talk to the server. I am raising the config dict issue and will add server type there. After that we can merge it accordingly.

**Comment by nsmgr8** [comment]
I have added the auth_type. It would be great if you could modify the pull request accordingly.

Thanks.

**Pull request closed without merging**
